name = "wujiaming88"
compatibility_date = "2026-08-25"
main = "src/index.js"

[assets]
directory = "./_site"
binding = "ASSETS"
not_found_handling = "404-page"
run_worker_first = ["/api/*"]

[observability]
enabled = true

[observability.logs]
enabled = true
invocation_logs = true
head_sampling_rate = 1
